### ISSUE TITLE
Test Query: eth-bridge exits and Dapp throws 'Objects are not valid as a React child' when formula is not supported

### ISSUE THREAD

**Issue by cryptomental** [MarketProject/Dapp#31]
'Happy path' for WolframAlpha query works fine, but for a not supported formula eth-bridge exits and Dapp throws:

![image](https://user-images.githubusercontent.com/20819151/35914746-af1bd6b4-0c04-11e8-8a05-791bce6441a2.png)

Steps to reproduce:

Introduction -> Oracle Data Source -> Oracle Query -> Select 'WolframAlpha' Datasource

Enter a not supported query, then

Eth-bridge error log:

```
[2018-02-07T11:07:06.740Z] INFO checking HTTP query 95d9ec629a368c14d083e601ac9098e840d2b8faff2fc85d1dc5a0d1f3f59d2c status on Thu Feb 08 2018 12:07:05 GMT+0100 (CET)
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/sandbox/ethereum-bridge/node_modules/web3/lib/web3/errors.js:38:16)
    at HttpProvider.send (/sandbox/ethereum-bridge/node_modules/web3/lib/web3/httpprovider.js:91:22)
    at RequestManager.send (/sandbox/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.send [as getBalance] (/sandbox/ethereum-bridge/node_modules/web3/lib/web3/method.js:145:58)
    at OracleInstance.checkAccountBalance (/sandbox/ethereum-bridge/lib/bridge-core.js:101:38)
    at Timeout._onTimeout (/sandbox/ethereum-bridge/lib/address-watcher.js:18:39)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)

Please wait...
To load this instance again: node bridge --instance oracle_instance_20180207T115952.json
Exiting...
```

I tried to reproduce after restart but it was fine, so it would be good to find a 100% reproducible scenario, perhaps truffle migrate and eth-bridge must be restarted. Reported on master @ ba273c142181102005ae127c3e811099e419c26f.

**Comment by perfectmak** [comment]
@cryptomental this has been fixed in #26 . 
As soon as it is merged, we can test and see if this issue should be closed.

**Comment by cryptomental** [comment]
@perfectmak great news, I will test the fix tomorrow.

**Comment by cryptomental** [comment]
I could not reproduce it, looks like it was indeed resolved.
